---
title: "Week 1 Notes"
author: "Andrew Abisha Hu"
date: "8/18/2018"
output: html_document
---
## Summary:

**Week 1 covers basic assigning values, subsetting with conditions, and simple way to check missing values.**


Reading url:
```{r }
Con <-url("http://www.jhsph.edu" ,"r" )
Con
x<- readLines(Con)
head(x)
```

Subsetting:
```{r }
# double braket can be used for computed index

x<- list(foo=1:4, bar=0.6, baz= "hello")
x$bar
x$foo
name <- "foo"
x[[name]]

x<- list(a= list(10,12,14), b=c(3.14,2.81))
x[[c(1,3)]]

x[[c(2,1)]]

x<- matrix(1:6, 2,3 )

x[1,2]
x[1,]
x[,2]

#Return the matrix
x[1,2,drop=F]
x[2, ,drop=F]

#Partial matching
x<- list(adjdofjodaif= 1:5)
x$a
x[["a"]]
x[["a", exact=F]]

#Removing NA values
x<- c(1,2,3,NA,NA,5)
bad<- is.na(x) #create a logical vector
x[!bad]

#choosing non NA values
y<- c("a", "b","c", NA, NA,"d")

good<- complete.cases(x,y)
x[good]
y[good]
```


Logical:
```{r}
#Double equal sign tests the equality 
x <- c(17, 14, 4, 5, 13, 12, 10)
x[x > 10]<- 4
x[x == 10] <-4
x
#Multiple conditions subsetting
ex<- hw1[hw1$Ozone>31 & hw1$Temp>90, ]
summary(hw1[hw1$Month==5,])
```

