---
title: "Getting and Cleaning data-Week2"
output: html_document
author: Andrew Abisha Hu
---
## **Content:** 
1. Connect mySQL
2. Reading HDF5
3. Reading data from web


**Reading MySQL**
```{r , include=FALSE}
library(RMySQL)
ucscDb<- dbConnect(MySQL(),user="genome",host="genome-mysql.cse.ucsc.edu")
result<- dbGetQuery(ucscDb,"show databases;"); dbDisconnect(ucscDb);

result
#connect
hg19<- dbConnect(MySQL(),user="genome",db="hg19",host="genome-mysql.cse.ucsc.edu")
allTables<- dbListTables(hg19)
length(allTables)

allTables[1:5]

dbGetQuery(hg19, "select count(*) from affyU133Plus2")

affyData<- dbReadTable(hg19,"affyU133Plus2")
head(affyData)

#select the subset of the data
query<- dbSendQuery(hg19, "select * from affyU133Plus2 where misMatches between 1 and 3")

affyMis <- fetch(query); quantile(affyMis$misMatches)

affyMisSmall <- fetch(query, n=10); dbClearResult(query) #remember to clear 

dim(affyMisSmall)

affyMisSmall

#close the connection
dbDisconnect(hg19)
```


**Reading HDF5**
```{r , include=FALSE}
source("http://bioconductor.org/biocLite.R")
biocLite("rhdf5")

library(rhdf5)
created= h5createFile("example.h5")
created
```

**Reading data from the web**
```{r , include=FALSE}
#Read the url
con = url("http://scholar.google.com/citations?users=HI-I6C0AAAAJ&hl=en")
htmlCode = readLines(con)
close(con)
htmlCode


#Parsing with XML
library(XML)
url <- "http://scholar.google.com/citations?users=HI-I6C0AAAAJ&hl=en"

html <- htmlTreeParse(url,useInternalNodes = TRUE)
xpathSApply(html,"//title", xmlValue)


#Get from httr package
library(httr); html2= GET(url)
content2 = content(html2,as ="text")
parsedHtml = htmlParse(content2,asText= TRUE)
xpathSApply(parsedHtml,"//title", xmlValue)

```