---
title: "R_Programming_Week3"
output: html_document
---
The Loop functions:

Apply:
```{r }
#Apply (Margin 1 indicates row, 2 is cols)
library(datasets)
apply(iris[, 1:4], 2, mean)

#mapply: apply functions to multiple vector
str(mapply)

#tapply: apply functions to subset of a vector
str(tapply) #index is a factor, or a list of factor
data("mtcars")

#How can one calculate the average miles per gallon (mpg) by number of cylinders in the car (cyl)?

tapply(mtcars$mpg,mtcars$cyl,mean)

#split takes a vector or other objects and splits it into groups
str(split) #x= vector or df, f= factor or list of factor, drop= empty factors levels should be dropped?

x<- c(rnorm(10),runif(10),rnorm(10,1))
f<- gl(3,10)
split(x,f)

#combine with lapply (the same with using just tapply)
lapply(split(x,f),mean)
tapply(x,f,mean)

#examples
library(datasets)
head(airquality)

#split the data into monthly basis

s<- split(airquality,airquality$Month)

#applying with anonymous functions
lapply(s,function(x) colMeans(x[, c("Ozone","Solar.R","Wind")]))

sapply(s,function(x) colMeans(x[,c("Ozone","Solar.R","Wind")]))

sapply(s,function(x) colMeans(x[,c("Ozone","Solar.R","Wind")],na.rm=TRUE))




```

Debugging tools intro

```{r}
#traceback() : gives you the latest error




```



```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
