---
title: "Week4 Notes.RMD"
output: html_document
---
Case Study: Samsung
```{r }
library(data.table)
sam<- load("/users/andrewhu/desktop/samsungData.rda")
names(sam)[1:12]


#average acceleration for each subject
par(mfrow=c(1,2) , mar=c(5,4,1,1))
sam<- transform(sam, activity= factor(activity))
sub1 <- subset(sam, subject==1)
plot(sub1[,1], col= sub1$activity, ylab= names(sub1)[1])
plot(sub1[,2], col= sub1$activity, ylab= names(sub1)[2])
legend("bottomright", legend= unique(sub1$activity), col= unique(sub1$activity), pch=1)


#Plotting max acceleration for the first subject

par(mfrow=c(1,2))
plot(sub1[,10], pch=19, col=sub1$activity, ylab = names(sub1)[10])
plot(sub1[,11],pch=19, col=sub1$activity, ylab=names(sub1)[11])


#SVD::

svd1 <- svd(scale(sub1[,-c(562,563)]))
par(mfrow = c(1,2))
plot(svd1$u[,1], col=sub1$activity, pch=19)
plot(svd1$u[,2], col=sub1$activity, pch=19)


#k-means 
kClust<- kmeans(sub1[,-c(562,563)], centers =6, nstart=100)
table(kClust$cluster, sub1$activity)

#k-means setting a nstart
kClust<- kmeans(sub1[,-c(562,563)], centers =6)
table(kClust$cluster, sub1$activity)

```


Case Study: Air pollution
```{r }
#Reading table 1999
pm0<- read.table("/users/andrewhu/desktop/pm25_data/RD_501_88101_1999-0.txt", comment.char = "#", header= FALSE, sep ="|", na.strings= "")
dim(pm0)
head(pm0)

#read the first line for names
cnames<- readLines("/users/andrewhu/desktop/pm25_data/RD_501_88101_1999-0.txt",1)
cnames #not splitted yet.

#split by |
cnames<- strsplit(cnames, "|", fixed= TRUE)
cnames #check


#Assign names to the table
names(pm0) <- cnames[[1]]
head(pm0) #there are some names with blanks, which is not valid

#Making legible names
names(pm0) <- make.names(cnames[[1]])
head(pm0) #now the blanks are replaced with .


#basic checking----

x0 <- pm0$Sample.Value
class(x0)
str(x0)
summary(x0)

#checking missing values
mean(is.na(x0)) #11% are missing


#pm1

#Reading the second table
pm1<- read.table("/users/andrewhu/desktop/pm25_data/RD_501_88101_2012-0.txt", comment.char = "#", header= FALSE, sep ="|", na.strings= "")

dim(pm1)

names(pm1)<- make.names(cnames[[1]])
head(pm1)

#Simply compare.
x1 <- pm1$Sample.Value
summary(x1) #Note: median 7.63, lower than 1999. the min is negative, kinda strange.
str(x1)
mean(is.na(x1)) #5% missing values, less than 1999

#boxplot
boxplot(x0,x1)
boxplot(log10(x0),log10(x1)) 

#Examing negative values
negative <- x1<0
str(negative)
sum(negative, na.rm=TRUE)#total NA
mean(negative, na.rm=TRUE) #the proportion of NA


#dates, examing and transforming
dates<- pm1$Date
str(dates)
dates<- as.Date(as.character(dates),"%Y%m%d")
str(dates)

hist(dates,"month")
hist(dates[negative], "month")#check which period has more negative values


#####   Check monitors for one location only:   NY####

site0 <-unique(subset(pm0, State.Code==36, c(County.Code, Site.ID)))

site1 <- unique(subset(pm1, State.Code==36, c(County.Code, Site.ID)))

head(site0)

#paste county code and site ID together
site0 <- paste(site0[,1], site0[,2],sep=".")
site1 <- paste(site1[,1], site1[,2],sep=".")
str(site0)
str(site1)

#Finding the intersect bewteen site0 and site1
both<- intersect(site0,site1)
both

#Also , finding obs in each monitors

#Create a var for pasting the county code and site ID
pm0$county.site <- with(pm0, paste(County.Code, Site.ID, sep="."))

pm1$county.site <- with(pm1, paste(County.Code, Site.ID, sep="."))

#Subset to just NYC
cnt0 <- subset(pm0, State.Code==36 & county.site %in% both)
cnt1 <- subset(pm1, State.Code==36 & county.site %in% both)

head(cnt0)


#Split by county.side
split(cnt0, cnt0$county.site) #not useful

#Counting the rows , spliting by county site
sapply(split(cnt0, cnt0$county.site), nrow)
sapply(split(cnt1, cnt1$county.site), nrow)

#Targeting on one monitor: 63.2008
pm0sub <-subset(pm0, State.Code==36 & County.Code==63 & Site.ID == 2008)

pm1sub <-subset(pm1, State.Code==36 & County.Code==63 & Site.ID == 2008)

dim(pm1sub)
head(pm1sub)
dim(pm0sub)

#Plot the dates and pm25 value
dates1 <- pm1sub$Date
dates1 <- as.Date(as.character(dates1),"%Y%m%d")
x1sub <- pm1sub$Sample.Value
str(dates1)
plot(dates1, x1sub)


dates0 <- pm0sub$Date
dates0 <- as.Date(as.character(dates0),"%Y%m%d")
x0sub <- pm0sub$Sample.Value
plot(dates0, x0sub)



#Panel plot
par(mfrow= c(1,2), mar= c(4,4,2,1))

plot(dates0,x0sub, pch=20)
abline(h=median(x0sub,na.rm=T))

plot(dates1,x1sub, pch=20)
abline(h=median(x1sub,na.rm=T))


#Put the two plots on the same range
range(x0sub,x1sub, na.rm=T)
rng<- range(x0sub,x1sub, na.rm=T)

par(mfrow= c(1,2))
plot(dates0,x0sub, pch=20, ylim=rng)
abline(h=median(x0sub, na.rm=T))


plot(dates1,x1sub, pch=20, ylim=rng)
abline(h=median(x1sub, na.rm=T))




##### Look at each individual states

###See if each individual states improve or not across the years###




#Take avg value by state : perfect timing for using tapply

mn0<- with(pm0, tapply(Sample.Value, State.Code, mean, na.rm=T))
summary(mn0)

mn1<- with(pm1, tapply(Sample.Value, State.Code, mean, na.rm=T))
summary(mn1)


#Create DF
d0<- data.frame(state= names(mn0), mean=mn0)
d1<- data.frame(state= names(mn1), mean=mn1)


mrg <- merge(d0,d1, by="state")
dim(mrg)
head(mrg)

#Plot the data####

par(mfrow=c(1,1))
with(mrg, plot(rep(1999,52), mrg[,2],xlim= c(1998,2013)))
with(mrg, points(rep(2012,52), mrg[,3],xlim= c(1998,2013)))
segments(rep(1999,52), mrg[,2],rep(2012,52), mrg[,3])


```


