---
title: "Presentation Notes"
author: "Andrew Abisha Hu"
date: "8/15/2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## my new slide

Plain text

*italicized text*

**Bold**

` this is for code demo for ( i %in% 1:10) `

```{r, comment=""}
head(mtcars)
```

## my second new slide

** Add a plot without presenting the code **

```{r, echo=F, fig.align='center', fig.cap="My FIGURE"}
plot(mtcars$wt, mtcars$mpg, xlab= "weight", ylab="MPG")
```

## my title

- Bullet one
- Bullet 2

1. item a
2. item b

### A top level subheading

#### A second level subheading

## My first map

```{r, echo=F}
library(leaflet)
my_map <- leaflet() %>% 
        addTiles()
my_map
```

## Add Markers

```{r, echo=FALSE}
library(leaflet)
my_map <- my_map %>%
  addMarkers(lat=39.2980803, lng=-76.5898801, 
             popup="Jeff Leek's Office")
my_map
```


## Adding Many Markers

```{r, echo=FALSE}
set.seed(2016-04-25)
df <- data.frame(lat = runif(20, min = 39.2, max = 39.3),
                 lng = runif(20, min = -76.6, max = -76.5))
df %>% 
  leaflet() %>%
  addTiles() %>%
  addMarkers()
```


## Mapping clusters: too close? No problem

```{r, eval=FALSE}
df <- data.frame(lat = runif(500, min = 39.25, max = 39.35),
                 lng = runif(500, min = -76.65, max = -76.55))
df %>% 
  leaflet() %>%
  addTiles() %>%
  addMarkers(clusterOptions = markerClusterOptions())
```